class ABTestingFormMiddleware(object):
    """
    Ensure that forms submitted with the hidden field generated by the
    templatetag record the choice of the test varient.
    
    """
    
    def process_view(self, request, *args, **kwargs):
        raise NotImplementedError("Need to record!")
